version: "3"
services:
  ql_web:
    image: whyour/qinglong:latest
    container_name: ql
    ports:
      - "0.0.0.0:5700:5700"
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
    tty: true
    restart: always

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
